### ISSUE TITLE
Missing command for alt+up and alt+down

### ISSUE THREAD

**Issue by nikomikulicic** [stevemoser/vscode-xcode-keybindings#7]
Hi!

I'm wondering what these two commands should be doing:

```           
            {
                "key": "alt+up",
                "command": "",
                "when": "editorTextFocus && !editorReadonly"
            },
            {
                "key": "alt+down",
                "command": "",
                "when": "editorTextFocus && !editorReadonly"
            },

```

I've added a temporary fix to ignore these key bindings in `keybindings.json` since they're eating up the current commands I've had on this key combination. Fix:

```
    {
        "key": "alt+up",
        "command": "-"
    },
    {
        "key": "alt+down",
        "command": "-"
    }
``` 

Nevertheless, it would be nice if they had a function or if they were removed.

**Comment by stevemoser** [comment]
@nikomikulicic Thanks for finding that. I added Xcode's shortcut for Opt+Up and Opt+Down which work like Home and End. I created #8 to prevent this in the future when I get around to it.
